server:
  port: 8090
  max-http-request-header-size: 65536


# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flashbuy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 16 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（负值表示无限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml # mapper.xml文件路径
  type-aliases-package: com.zljin.flashbuy.domain # 实体类路径
  global-config:
    db-config:
      id-type: ASSIGN_ID # 主键生成策略，ASSIGN_ID通常配合雪花算法使用
  configuration:
    map-underscore-to-camel-case: true # 自动开启驼峰命名映射
    cache-enabled: false # 关闭二级缓存

logging:
  level:
    root: info